# Generated by Django 4.0.5 on 2022-06-13 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='h1',
        ),
    ]
