# Generated by Django 4.0.5 on 2022-06-15 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_url_post_slug_alter_post_tags_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='slug',
            new_name='url',
        ),
    ]
